"""study material subject

Revision ID: a97112134a27
Revises: ad9c1a82fb51
Create Date: 2026-10-02 12:41:56.983827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97112134a27'
down_revision: Union[str, Sequence[str], None] = 'ad9c1a82fb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
