"""initial schema

Revision ID: ad9c1a82fb51
Revises: 
Create Date: 2026-10-01 19:43:53.602452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9c1a82fb51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misconceptions',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('common_wrong_options', sa.JSON(), nullable=False),
    sa.Column('remediation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misconceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misconceptions_topic'), ['topic'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('avatar', sa.String(length=20), nullable=False),
    sa.Column('tiara_count', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('noskip_count', sa.Integer(), nullable=False),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('mistakes_corrected', sa.Integer(), nullable=False),
    sa.Column('beliefs', sa.JSON(), nullable=False),
    sa.Column('cursors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('badges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_badge_once')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_user_id'), ['user_id'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('certificate_url', sa.String(length=200), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('students', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_user_id'), ['user_id'], unique=False)

    op.create_table('rewards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('ref', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'ref', name='uq_reward_once')
    )
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rewards_user_id'), ['user_id'], unique=False)

    op.create_table('study_materials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('extracted_sections', sa.JSON(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('topic', sa.String(length=40), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_materials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_materials_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_materials_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('study_material_id', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option', sa.String(length=2), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('accepted_answers', sa.JSON(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=True),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=False),
    sa.Column('diagnostic_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_material_id'], ['study_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_study_material_id'), ['study_material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic'), ['topic'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=40), nullable=False),
    sa.Column('client_key', sa.String(length=64), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('selected_option', sa.String(length=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_key', name='uq_attempt_client_key')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('selected_option', sa.String(length=2), nullable=False),
    sa.Column('belief_before', sa.JSON(), nullable=False),
    sa.Column('belief', sa.JSON(), nullable=False),
    sa.Column('initial', sa.JSON(), nullable=False),
    sa.Column('final', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('reasoning_evidence', sa.JSON(), nullable=False),
    sa.Column('slip_kind', sa.String(length=30), nullable=True),
    sa.Column('primary_hypothesis', sa.String(length=30), nullable=True),
    sa.Column('alternative_hypotheses', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('initial_confidence', sa.Float(), nullable=False),
    sa.Column('followup_question_id', sa.String(length=40), nullable=True),
    sa.Column('followup_response', sa.Text(), nullable=True),
    sa.Column('final_diagnosis', sa.String(length=30), nullable=True),
    sa.Column('misconception_id', sa.String(length=60), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('retry', sa.JSON(), nullable=False),
    sa.Column('understanding', sa.Float(), nullable=True),
    sa.Column('corrected', sa.Boolean(), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostic_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('followup_questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('diagnostic_session_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=40), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('hypothesis_a', sa.String(length=120), nullable=False),
    sa.Column('hypothesis_b', sa.String(length=120), nullable=False),
    sa.Column('expected_signal_a', sa.Text(), nullable=False),
    sa.Column('expected_signal_b', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('gain', sa.Float(), nullable=False),
    sa.Column('response', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followup_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followup_questions_diagnostic_session_id'), ['diagnostic_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followup_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followup_questions_diagnostic_session_id'))

    op.drop_table('followup_questions')
    with op.batch_alter_table('diagnostic_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_topic'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_question_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostic_sessions_created_at'))

    op.drop_table('diagnostic_sessions')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_question_id'))
        batch_op.drop_index(batch_op.f('ix_attempts_created_at'))

    op.drop_table('attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic'))
        batch_op.drop_index(batch_op.f('ix_questions_study_material_id'))
        batch_op.drop_index(batch_op.f('ix_questions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_questions_created_at'))

    op.drop_table('questions')
    with op.batch_alter_table('study_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_materials_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_materials_processing_status'))
        batch_op.drop_index(batch_op.f('ix_study_materials_created_at'))

    op.drop_table('study_materials')
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rewards_user_id'))

    op.drop_table('rewards')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_created_at'))

    op.drop_table('evaluation_runs')
    op.drop_table('certificates')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_user_id'))

    op.drop_table('badges')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('misconceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misconceptions_topic'))

    op.drop_table('misconceptions')
    # ### end Alembic commands ###
